### ISSUE TITLE
[DOCS]: META: Doc improvements for stack v7.12

### ISSUE THREAD

**Issue by DonNateR** [elastic/ecs#1206]
Below is a list of improvements the docs team wishes to make to the ECS docs before 1.9. The items in this list are based on a [brainstorming session](https://docs.google.com/document/d/1zIpQG8Flq1pVpV4TOGYolGfqP2lTGeVrxCbZkZsfmeo/edit?usp=sharing) conducted by the ECS team.

- [ ] (Nice to have) Add a note about making an issue for field table doc fixes, instead of editing the asciidoc or jinja files. Might not be relevant after doc redesign.
- [ ] Improve the mapping walkthrough for common existing log event types. A version of this exists already in https://www.elastic.co/guide/en/ecs/current/ecs-getting-started.html . For common log types (such as Filebeat or Logstash), sync with the Logstash team to ensure that ECS mapping is covered in their documentation.
- [ ] Categorize ECS fieldsets by templates/categories and create instructions on how to compose an ECS template. Use this internal doc https://github.com/elastic/ecs/tree/master/generated/elasticsearch#how-to-compose-templates.
- [ ] Add notes to each ECS fieldsets about which persona or solution the fieldset relates to. 
    - End-user who simply reads or uses fields within Kibana, such as a security analyst. Probably won't be familiar with how ECS fits into the stack.
    - Power-user who manage Elastic Stacks or install agents on devices. Tend to be more knowledgeable and curious about mapping and custom fields.
    - Elastic developers (employees or a third party), people who want to support ECS in the Elastic solutions. 
    - See the "Persona" section of this Google Doc: https://docs.google.com/document/d/1bSLKlvO2Atc4QNOqQ4YpNWL2cZ8eRkrNgFYc47477JM/edit#heading=h.9fmdnfbxyrhg
- [ ] Streamline field descriptions so that they don't include the word "field" in each description.
- [ ] Add more common usage guides. https://www.elastic.co/guide/en/ecs/1.x/ecs-user-usage.html#ecs-user-usage-categorization

**Comment by ebeahan** [comment]
Will revisit these doc improvements in the future.
