### ISSUE TITLE
Post GA tasks

### ISSUE THREAD

**Issue by ruflin** [elastic/ecs#160]
First here are some issue I've moved out of the initial 1.0 plan.

- [ ] Introduce `related.*` field set (#67)
- [ ] Discuss nesting `http` (and eventually all network protocol field sets) under `network`?
- [ ] increase ignore_above (#105)
- [ ] Add facility, severity, priority to log or event (closes #36)
- [ ] threat & vulnerability TLOs (#113)
  - new top level objects
- [ ] Add a few fields to `user` object (#117)
- [ ] event.start/end/duration (pr #80)
- [ ] thread and process ids and xids (#82)
  - [ ] Add thread name? (idea from unrelated #97)
  - [ ] Add process.path and process.path.keyword
- [ ] Add tag field `status` to log (see #100 & related issues)
- [ ] tag field for booleans (#100)
  - [ ] make it so for log, document a few expected tags
- [ ] Add missing fields to host from Beats' add_host_md (#75)
- [ ] log4j's logger, module, context, class (#97), extended?
- [ ] APM: span_id, trace_id (#99), extended?
- [ ] add cidr and subnet (386, pr #111)
- [ ] session (#37, pr #43)
- [ ] connection TLO (pr #51)
- [ ] forwarding IP (#40)
- [ ] cli/srv (#63, see #51)
- [ ] network stats directionality (pr #2)

Here are some issues that I don't consider critical to hitting 1.0.

- field length limits (#23)
- dhcp use case (#61)
- TLS cert meta-data (#64)
- anonymization/pseudonymization (#68)
- transport meta-data (similar to forwarder?) (#76)
- "time" / Adding support for data format (e.g. units) (see #77)
- transaction.id
- ECS-ness (#98)
- `context` top level object from EMR document (not in the votes, no details)
- F5 use case (pr #59)

**Comment by ruflin** [comment]
I'm closing this issue as it's basically a summary of Github issues and I don't think we need that.
