### ISSUE TITLE
Beta1 related but not blocker tasks

### ISSUE THREAD

**Issue by ruflin** [elastic/ecs#161]
## Misc

- [x] Domain breakdown field (adding the field for domain without subdomain) #163
- [ ] Reflect object reuse in template.json
- [ ] Reflect object reuse in schema.csv
- [x] Fix script issue with `multi_fields`, introduced when adding for Core/Extended
- [x] Discuss whether we nest protocol field sets under `network.`
  - [ ] Add field set for `dns`
  - [x] Re-introduce `http` (see removal #171)
- [x] Re-introduce `user_agent` (see removal #172)

## Documentation

- [ ] Non-ECS fields (#114, #130, #101)
  - [ ] Document how to work around ECS (#114, #130)
  - [ ] Decide on specific approach(es) (#101)
  - [ ] sharing schema examples with non-ECS data (doc) (#52)
    - this issue contains discussion about naming outside ECS
- [x] list upcoming top level fields as prevention measure vs customization clashes
- [ ] Readme should suggest strategy of getting to ECS compatibility in two phases:
  1. Map your stream's existing fields to ECS
  2. Consider "filling" more ECS fields than you had initially, if it can be done easily from that system's vantage point
- [ ] Cleanup ECS use cases v new names (#110, let's do close to v1.0, when things are closer to GA)
- [ ] development pointers (#92)

## Related Projects

- [ ] Share template with Beats
- [ ] Open PRs
  - [ ] Beats
    - [ ] Document breaking changes (see elastic/beats#8313)
    - [ ] Packetbeat elastic/beats#7968
    - [ ] More issues for default fields & popular modules
  - [ ] Logstash plugins
    - [ ] user_agent (closes #112)
    - [ ] GeoIP
    - [ ] Create issues for all other Elastic-supported plugins
    - [ ] Update the CEF codec? Add an option to convert?
  - [ ] ES Ingest Node processors
    - [ ] user_agent
    - [ ] GeoIP
    - [ ] Any other needed?

## Automation

- [ ] Script to generate an ECS index template (related: #95)
  - [ ] Option to generate separate fields.yml files (core only, core+ext)
- [ ] Offer a script that can look at existing ES index templates and evaluate for ECS compliance: breaking changes, unknown fields, etc
- [ ] Script and/or procedures to help migrate existing indices to ECS
  - Consider the following simplification/approach: implement one or a few pipelines that can automatically take known streams (Beats 6.x) and change them to ECS

## Close

Not necessarily related to 1.0, but during my review, these issues seemed to have been addressed or sound like we're not going to go that direction. So consider closing.

- [x] pr #2? network stats directionality
- [x] ~~pr #51? conn prefix~~ not closing it
- [x] pr #74? host.name stays hostname
- [x] #101

**Comment by MikePaquette** [comment]
@webmat @ruflin should we look at any of these items in light of beta2?

I know I'd still like to see us reflect object reuse in schema.csv . :-)

**Comment by ruflin** [comment]
@MikePaquette I see all the above issues as tooling / docs around ECS that can also be backported from master to the 1.0 branch after we cut off beta2. Some of the above definitively are need for the GA release.

**Comment by webmat** [comment]
Yes, the end of this week will be a bit weird. But starting next week, I'd like to get back to working on the tooling around ECS. Fixing schema.csv and template.json are definitely at the top of my list.

Looking at some of the other cool code contributions (from both Andrews) is also right in there :-)

**Comment by webmat** [comment]
Most of the tasks I see here have been done over the years 🎉 . Closing as stale
