### ISSUE TITLE
Rename the default branch from master to main

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#1643]
The ECS team will follow these steps to ensure a smooth transition when renaming the default branch  from `master` to `main`: 

- [x] #1644 Synchronize the new `main` branch using a GitHub Action workflow. [Example](https://github.com/elastic/kibana/blob/master/.github/workflows/sync-main-branch.yml)
- [x] https://github.com/elastic/docs/pull/2266 Update the docs build config to point to `main`. [Example](https://github.com/elastic/docs/blob/master/conf.yaml#L524)
- [x] Rename the default branch as explained in the [GitHub Docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch).
- [x] Update any branch protection rules for `master` to now apply to `main`.
- [x] Remove GitHub Action workflow synchronizing `master` to `main`.
