### ISSUE TITLE
Introducing the mandated values for the categorization fields

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#691]
This issue is meant to track the work required to introduce the mandated values for the currently reserved fields (event.kind, event.category, event.type, event.outcome).

**Introduction for ECS 1.4**

- [ ] #684 Initial plumbing (new pages, new YAML sections to list values & descriptions) 
- [ ] Introduce the initial set of values in the official ECS docs
- [ ] Publish the public Doc to capture feedback around additional values coming up
- [ ] Finalize the docs for categorization

**Follow-up work**

To be tracked here.

**Comment by webmat** [comment]
Added the public feedback document (https://ela.st/ecs-categories-draft) to the body of the pull request.

**Comment by enotspe** [comment]
It is not very clear the difference of `network `from `network_flow`. Or what could be an only `network `event and not a `network_flow` event?

**Comment by webmat** [comment]
@enotspe That's why these specific values are not out yet. They're some of the most important ones we still have to finish clarifying (hence the gradual release of these values).

By the way, this public doc is meant to accept comments from everyone. Could you confirm whether you're allowed to do that? You don't need to actually enter a comment, just want to double check that permissions are correctly set :-)

**Comment by enotspe** [comment]
@webmat yes, i can see and comment the doc. Should we comment there instead of here?

**Comment by webmat** [comment]
@enotspe Yes, you can comment in there, especially around the still unpublished values.

My recommendation for feedback would be:

- any comment very specific to what's currently published in the official ECS docs on www.elastic.co should be via a Github issue or PR
- any general comment on the general approach, future values, missing values, etc. should for now be on the public feedback document.
