### ISSUE TITLE
All examples that are a composite type (array, object) should be quoted, to avoid YAML interpreting them

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#781]
This issue mostly affects objects (like the example for `labels`). But it could also affect arrays, if for example we have an array that contains an unquoted `NO`, which would be interpreted by YAML as False, rather than the string "NO".

This issue not only affects the generated artifacts in the ECS repo, but also artifacts down the line, e.g. Beats starting from `generated/beats/fields.ecs.yml` and in turn generating various other artifacts.

- [x] #782 Immediate need is to fix `labels` to double quote it, an each values inside, to fix an issue in Beats
- [ ] #966 Fix all of the arrays
- [ ] #966 Add a linting rule or fail the build if any `example:` contains directly an array or an object, rather than a scalar.

**Comment by codebrain** [comment]
++ this would also help the .NET client where I have had to handle examples by "santizing" them so they can be safely written into XML comments:

https://github.com/elastic/ecs-dotnet/blob/dc0d44fe1b0b3028a6a1cec044c7d8b30d4423a7/src/Generator/SchemaExtensionMethods.cs#L18-L23

**Comment by gen0cide** [comment]
This definitely has created issues with trying to parse ECS YAML (both the source schema, as well as the generated).

Basically, the field has to get specified as:

```
type Definition struct {
  // ... other fields
  Example          interface{}     `config:"example"`
}
```
So normalizing this certainly removes that ugly workaround. Thanks!
