### ISSUE TITLE
ECS Core and ECS Extended

### ISSUE THREAD

**Issue by webmat** [elastic/ecs#93]
We've discussed creating a separation between the most stable and well understood fields (ECS Core) and the more experimental ones (ECS Extended). This issue is meant to have a discussion on how we should do this, and track the subtasks.

- [x] Write documentation explaining the difference between the two
- [x] Assign each field to one of the two levels (#133)
  - [x] Add the appropriate markings in all of the `schema/*.yml` files
- [x] Modify the scripts to support this new metadata about each field
  - [x] Output Level instead of Phase in the csv
  - [x] Output Level in a new column in the HTML
- Later, only if needed
  - Option to generate core only csv & template?
- ... (comment below for any other suggestion)

**Comment by webmat** [comment]
We've discussed two options about how to display Core vs Extended fields:

- Add a column in the tables that says "Core" or "Extended"
- Split the tables in two. So each section (e.g. [event](https://github.com/elastic/ecs#-event-fields)) would have a table of all "Core" fields, followed by a table of all "Extended" fields.

**Comment by webmat** [comment]
Another note: a field being marked as "Extended" is not a permanent thing. Rather it should be seen as a more experimental section of ECS, where things may change a bit more. When the community gels around the usage of a field or set of fields, they could be promoted to "Core", and be considered more stable.

**Comment by webmat** [comment]
Related to #54 as well. After Core & Extended, users of ECS have the option to add their custom fields for their use cases (without them being part of ECS).

**Comment by ruflin** [comment]
I started to play around a view options on how we could visualise it. I think the challenge is mainly on the UI side as in the fields.yml it would be just a flag. I took agent fields only as an example, does not mean it has to be split up.

Currently I prefer Option 2 and 3 over Option 1. One of the reasons to have Core and Extended is to give users new to ECS a smaller set of fields. If we mix them together under one title they see directly all to get started (this also might be a benefit). Also I assume there are going to be fields under prefixes like `agent` that are going to be extended but also full prefixes like `hash.*`. If we put it in under the same title, where would the full prefixes go?

The reason I like Option 3 is that it is similar to 1 but also brings benefits of 2. If we go with 3 we should have an indication in the table which of the fields are core (like bold or italic?).


# Option 1: Core and Extended under 1 title

## <a name="agent"></a> Agent fields

The agent fields contain the data about the agent/client/shipper that created the event.

### Core

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.version"></a>agent.version  | Version of the agent.  | keyword  |   | `6.0.0-rc2`  |
| <a name="agent.name"></a>agent.name  | Name of the agent.  | keyword  |   | `filebeat`  |
| <a name="agent.id"></a>agent.id  | Unique identifier of this agent (if one exists).<br/>Example: For Beats this would be beat.id.  | keyword  |   | `8a4f500d`  |

### Extended

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |


# Option 2: Core and Extended separate entries

## Core

### <a name="agent"></a> Agent fields

The agent fields contain the data about the agent/client/shipper that created the event.

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.version"></a>agent.version  | Version of the agent.  | keyword  |   | `6.0.0-rc2`  |
| <a name="agent.name"></a>agent.name  | Name of the agent.  | keyword  |   | `filebeat`  |
| <a name="agent.id"></a>agent.id  | Unique identifier of this agent (if one exists).<br/>Example: For Beats this would be beat.id.  | keyword  |   | `8a4f500d`  |

### <a name="agent"></a> Host fields

....

## Extended

### <a name="agent"></a> Agent fields

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |

### <a name="agent"></a> Host fields

....


# Option 3: Core and Extended but extended with all entries

## Core

### <a name="agent"></a> Agent fields

The agent fields contain the data about the agent/client/shipper that created the event.

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.version"></a>agent.version  | Version of the agent.  | keyword  |   | `6.0.0-rc2`  |
| <a name="agent.name"></a>agent.name  | Name of the agent.  | keyword  |   | `filebeat`  |
| <a name="agent.id"></a>agent.id  | Unique identifier of this agent (if one exists).<br/>Example: For Beats this would be beat.id.  | keyword  |   | `8a4f500d`  |
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |

### <a name="agent"></a> Host fields

....

## Extended

### <a name="agent"></a> Agent fields

| Field  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|
| <a name="agent.version"></a>agent.version  | Version of the agent.  | keyword  |   | `6.0.0-rc2`  |
| <a name="agent.name"></a>agent.name  | Name of the agent.  | keyword  |   | `filebeat`  |
| <a name="agent.id"></a>agent.id  | Unique identifier of this agent (if one exists).<br/>Example: For Beats this would be beat.id.  | keyword  |   | `8a4f500d`  |
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |

### <a name="agent"></a> Host fields

....

**Comment by ruflin** [comment]
One note I would like to add for Extended: From my perspective in Extended can be fields that never should end up in Core. So it could be either fields that potentially "incubate" into core in the future or fields that are there to stay.

**Comment by ruflin** [comment]
In #95 @robgil just brought up a very interesting proposal (not sure if intentional). Instead of only having `core` and `extended` we could also have `application` (or service). We discussed in the past where services and protocols fit. Should they be prefixed by `service` and `protocol` for example? My personal opinion is that they shouldn't for usability reason. But what if we would have a `protocol` and `service` "category" besides Core and Extended? We could put all service related fields like k8s there and for the protocols like http, dns and others we would have `protocol` category. This would reduce the scope of Core and Extended.

**Comment by robgil** [comment]
++ @ruflin. The service/application schema layer will allow for infinite customization for specific services/applications and all their uncommon fields.

**Comment by ruflin** [comment]
I think we should for now only focus on Core and Extended. Everything that should go into App or Protocol should for now just go into Extended. This reduces the complexity for now and we can still introduce more layers later if needed.

**Comment by MikePaquette** [comment]
I don't think we should lump extended and application together, even temporarily.  ECS at v1.0 should define fields and namespaces/objects/prefixes sufficiently so that a compliant implementation will not have field/object conflicts in Elasticsearch.  I think three distinct classifications are necessary:

1. Core – A fully defined set of field names that exists under a defined set of ECS top-level objects.
2. Extended – A partially defined set of non-core field names that exist under the same set of ECS top-level objects.
3. App/Other – An undefined set of fields that exist under a restricted set of Non-ECS top-level objects.

![screen shot 2018-09-12 at 6 36 42 pm](https://user-images.githubusercontent.com/22619280/45456970-e2cc1d00-b6ba-11e8-89d5-28345c1ab126.png)

**Comment by webmat** [comment]
Back to the representation of Core vs Extended, here's an option 4, not shown in @ruflin's examples from Mid August:

### <a name="agent"></a> Agent fields

| Field  | ECS Level  | Description  | Type  | Multi Field  | Example  |
|---|---|---|---|---|---|
| <a name="agent.version"></a>agent.version  | Core | Version of the agent.  | keyword  |   | `6.0.0-rc2`  |
| <a name="agent.name"></a>agent.name  | Core | Name of the agent.  | keyword  |   | `filebeat`  |
| <a name="agent.id"></a>agent.id  | Core | Unique identifier of this agent (if one exists).<br/>Example: For Beats this would be beat.id.  | keyword  |   | `8a4f500d`  |
| <a name="agent.ephemeral_id"></a>agent.ephemeral_id  | Extended | Ephemeral identifier of this agent (if one exists).<br/>This id normally changes across restarts, but `agent.id` does not.  | keyword  |   | `8a4f500f`  |

I wasn't sure what to name the column itself, so I just named it "ECS Level" for now. Suggestions welcome :-)

What I like about this approach is that it avoids potential edge case situations like when an object is 100% extended, and we may miss that we're looking at a table only of Extended attributes, or when an object has exactly one Core or Extended attribute, and we end up with a strange table with one header line and only one data line :-)

The only disadvantage I see to this representation is that it makes the table a bit wider, and will likely require sideways scrolling. You can also see these two commits to visualize different approaches,  in the actual readme [table per level](https://github.com/webmat/ecs/blob/a268e8c/README.md#-event-fields) vs [column with level](https://github.com/webmat/ecs/blob/846e9d1/README.md)

But I think the simplicity of this approach outweighs this disadvantage. Option 4 is the one I would prefer.

**Comment by ruflin** [comment]
I'm ok with the above visual approach. The main downside I see is that people coming to ECS will see core and extended directly together on their first visit, at the same time this could be a benefit too. We should just start with one version and then see how it evolves.
