### ISSUE TITLE
Categorization Fields GA

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#942]
#### Summary

Move the ECS categorization fields from beta to GA

#### Task List

- [x] #1067 Remove the `beta` warning label from the ECS categorization documentation
- [x] Capture any outstanding discussion, possible future enhancements, etc. from https://ela.st/ecs-categories-draft. Any future proposals and accompanying discussions should be handled through the ECS RFC process.
- [x] #963 Add additional event category allowed value: `configuration` addressing #799
- [x] #1040 Add additional event category allowed value: `registry` addressing #1019 
- [x] #1049 Add additional event category allowed value: `session` as mentioned in in-progress `session` RFC #935

**Comment by webmat** [comment]
Let's consider adding event category "configuration" as part of this. See  #799

**Comment by ebeahan** [comment]
Another `event.category` candidate value: `email`.

I've captured this as an idea that can be discussed further in the current `email` RFC https://github.com/elastic/ecs/pull/999#discussion_r515356516

**Comment by ebeahan** [comment]
Closing with the merging of #1067.
